parent(ton,yam).
parent(jame,sine).
male(jame).
father(X,Y):-parent(X,Y),male(X).
/*
Parent(Naree,Yam).
Parent(Ohm,Ji).
Parent(Nudee,Ji).
Male(Ton).
Male(Ohm).
Male(Ji).
Female(Yam).
Female(Naree).
Female(Nudee).
Parent(Ohm,Jame).
Parent(Ohm,Pin).
Parent(Ohm,Jo).
Parent(Ton,Pang).
Parent(Nudee,Jame).
Parent(Nudee,Pin).
Parent(Nudee,Jo).
Parent(Naree,Pang).
Male(Jame).
Male(Jo).
Female(Pin).
Female(Pang).
Parent(Ji,Sine).
Parent(Yam,Sine).
Brother(Jo,Ji).
Brother(Jame,Ji).
Older(Jo,Ji).
Younger(Jame,Ji).
Sister(Pin,Ji).
Older(Pin,Ji).
Sister(Pang,Yam).
Younger(Pang,Yam).
*/
